# Generated by Django 3.2.1 on 2021-05-06 05:34

import TwinCamera.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bg', models.ImageField(blank=True, null=True, upload_to=TwinCamera.models.path_and_rename)),
                ('img1', models.ImageField(blank=True, null=True, upload_to=TwinCamera.models.path_and_rename)),
                ('img2', models.ImageField(blank=True, null=True, upload_to=TwinCamera.models.path_and_rename)),
                ('img3', models.ImageField(blank=True, null=True, upload_to=TwinCamera.models.path_and_rename)),
                ('img4', models.ImageField(blank=True, null=True, upload_to=TwinCamera.models.path_and_rename)),
                ('img5', models.ImageField(blank=True, null=True, upload_to=TwinCamera.models.path_and_rename)),
                ('img6', models.ImageField(blank=True, null=True, upload_to=TwinCamera.models.path_and_rename)),
            ],
        ),
    ]
