# Generated by Django 3.2.1 on 2021-05-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwinCamera', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='id',
            new_name='ID',
        ),
    ]
