# Generated by Django 3.2 on 2021-05-01 06:18

import TwinCamera.models
import TwinCamera.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('TwinCamera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='bg',
            field=models.ImageField(blank=True, null=True, storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='image',
            name='img1',
            field=models.ImageField(blank=True, null=True, storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='image',
            name='img2',
            field=models.ImageField(blank=True, null=True, storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='image',
            name='img3',
            field=models.ImageField(blank=True, null=True, storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='image',
            name='img4',
            field=models.ImageField(blank=True, null=True, storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='image',
            name='img5',
            field=models.ImageField(blank=True, null=True, storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='image',
            name='img6',
            field=models.ImageField(blank=True, null=True, storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AddField(
            model_name='image',
            name='sid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
