# Generated by Django 3.0.8 on 2021-04-24 15:50

import TwinCamera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwinCamera', '0002_auto_20210424_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='bg',
            field=models.ImageField(default='download.png', upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img1',
            field=models.ImageField(default='download.png', upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='image',
            name='img2',
            field=models.ImageField(default='download.png', upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='image',
            name='img3',
            field=models.ImageField(default='download.png', upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='image',
            name='img4',
            field=models.ImageField(default='download.png', upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='image',
            name='img5',
            field=models.ImageField(default='download.png', upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='image',
            name='img6',
            field=models.ImageField(default='download.png', upload_to=TwinCamera.models.path_and_rename),
        ),
    ]
