# Generated by Django 3.2 on 2021-05-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwinCamera', '0002_auto_20210501_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='sid',
        ),
    ]
