# Generated by Django 3.2.1 on 2021-05-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TwinCamera', '0002_rename_id_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='ID',
            new_name='id',
        ),
    ]
