# Generated by Django 3.2 on 2021-04-26 06:45

import TwinCamera.models
import TwinCamera.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwinCamera', '0005_auto_20210425_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='bg',
            field=models.ImageField(default='download.png', storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='image',
            name='img1',
            field=models.ImageField(default='download.png', storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='image',
            name='img2',
            field=models.ImageField(default='download.png', storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='image',
            name='img3',
            field=models.ImageField(default='download.png', storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='image',
            name='img4',
            field=models.ImageField(default='download.png', storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='image',
            name='img5',
            field=models.ImageField(default='download.png', storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='image',
            name='img6',
            field=models.ImageField(default='download.png', storage=TwinCamera.storage.OverwriteStorage(), upload_to=TwinCamera.models.path_and_rename),
        ),
    ]
